---
- name: Power on Dell server
  hosts: idrac
  connection: local
  gather_facts: no
  
  tasks:
    - name: Power on the server
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ idrac_ip }}"
        username: "root"
        password: "r0gerwilc0"
          #username: "{{ idrack_user }}"
          #password: "{{ idrac_password }}"
        validate_certs: False
        reset_type: "On"
      register: results

    - name: Show results
      debug:
        var: results
