---
- name: PowerEdge Prechecks Tasks
  hosts: redfish_apis
  connection: local
  gather_facts: false

  tasks:

  - name: Assert that an expected condition is true (this is a chicago asset)
    assert:
      that:
          - "'Chicago' in results.redfish_facts.system.entries[0][1].AssetTag"
      success_msg: "Confirmed a Chicago asset"

  - name: Ensure the correct model is being used
    assert:
      that:
        - results.redfish_facts.system.entries[0][1].Model == "3500"
      success_msg: "Confrimed model 3500"
      fail_msg: "This does not appear to be a model 3500. Aborting."

  - name: Ensure the correct manufacurer is being used
    assert:
      that:
        - results.redfish_facts.system.entries[0][1].Manufacturer == "Contoso"
      success_msg: "Confirmed manufacturer Contoso"
      fail_msg: "This does not appear to be made by Contoso. Aborting!"
