---
- name: Learning to Use Ansible for Windows automation
  hosts: windows
  #connection: winrm   # we already mapped this in our inventory
  gather_facts: yes

  tasks:
  
    - name: What did gather_facts return?
      ansible.builtin.debug:
        var: ansible_facts

